Item1 = int(input("Price of Item1: "))
Item2 = int(input("Price of Item2: "))
Item3 = int(input("Price of Item3: "))
print("<---------------------------------------------------------------------")
print("--------------------------------------------------------------------->")
print("Discount Details")
d1 = int(input("Provie discount(in percentage) for the 1st saver combo: "))
d2 = int(input("Provie discount(in percentage) for the 2nd saver combo: "))
d3 = int(input("Provie discount(in percentage) for the 3rd saver combo: "))
print("<---------------------------------------------------------------------")
ComboPack1c = ((Item1 + Item2)*(d1/100))
ComboPack2c = ((Item1 + Item3)*(d2/100))
ComboPack3c = ((Item2 + Item3)*(d3/100))
SuperSaverc = ((Item1 + Item2 + Item3)*(28/100))
ComboPack1 = ((Item1 + Item2)-ComboPack1c)
ComboPack2 = ((Item1 + Item3)-ComboPack2c)
ComboPack3 = ((Item2 + Item3)-ComboPack3c)
SuperSaver = ((Item1 + Item2 + Item3)-SuperSaverc)
contact = int(input("Please Provide Your 10 digit contact Number: "))
print("The resulting catalogue is: ")
print("<---------------------------------------------------------------------")
print("--------------------------------------------------------------------->")
print("Delhi Days")
print("R-Block, Model Town 3")
print("Delhi: 110009")
print("<---------------------------------------------------------------------")
print("--------------------------------------------------------------------->")
print("Item                            Price(per Pack)")
print("|                               |")
print("Item1                          ",Item1)
print("Item2                          ",Item2)
print("Item3                          ",Item3)
print("ComboPack1                     ",ComboPack1)
print("ComboPack2                     ",ComboPack2)
print("ComboPack3                     ",ComboPack3)
print("SuperSaver                     ",SuperSaver)
print("<---------------------------------------------------------------------")
print("--------------------------------------------------------------------->")
print("For home deleivery, contact here: 9876543210")